version: "2.3"
services:
  gadc:
    image: gadc
    container_name: gadc
    depends_on:
      - postgres
    ports:
      - 80:80
    volumes:
      - ./storage:/home/app/webapp/storage
      - ./logs:/home/app/webapp/log
    environment:
      HOST: 127.0.0.1
  postgres:
    image: postgres:13.2
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "work_mem=128MB"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '!~!2020post!~!gres2020!~!'